# FastAPI application entry point — will be fully generated by the pipeline
from fastapi import FastAPI

app = FastAPI(title="{{PROJECT_NAME}}")


@app.get("/api/health")
async def health():
    return {"status": "ok"}
