#!/usr/bin/env bash
# Spectraal — Stage 9: Test
# =====================================================================
# Runs automated API tests against the deployed application using
# test cases generated by SpecPilot (specs/tasks.json).
#
# Input:  $PROJECT_DIR with deployed app (build-meta.json has ports)
# Output: test-report.json with pass/fail per test case
#
# Test flow:
#   1. Read test cases from specs/tasks.json (api_details)
#   2. Get backend port from build-meta.json
#   3. Run auth tests first (register → login → get token)
#   4. Run CRUD/protected tests with the JWT token
#   5. Generate test-report.json

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/lib/logging.sh"

log_step "9" "TEST"

PROJECT_DIR="${1:?Usage: 09-test.sh /path/to/project}"
SPECTRAAL_ROOT="${2:-$(cd "$SCRIPT_DIR/.." && pwd)}"

# ── Locate test cases ────────────────────────────────────────

TASKS_FILE=""
BUILD_DIR=$(dirname "$PROJECT_DIR")
if [ -f "$BUILD_DIR/specs/tasks.json" ]; then
  TASKS_FILE="$BUILD_DIR/specs/tasks.json"
elif [ -f "$PROJECT_DIR/specs/tasks.json" ]; then
  TASKS_FILE="$PROJECT_DIR/specs/tasks.json"
fi

if [ -n "$TASKS_FILE" ] && ! jq -e '.test_cases' "$TASKS_FILE" >/dev/null 2>&1; then
  log_warn "tasks.json exists but has no test_cases array"
  TASKS_FILE=""
fi

if [ -z "$TASKS_FILE" ]; then
  log_warn "No SpecPilot test cases found — running smoke test only"
fi

# ── Get backend port ─────────────────────────────────────────

BE_PORT=""
if [ -f "$PROJECT_DIR/build-meta.json" ]; then
  BE_PORT=$(jq -r '.ports.backend // empty' "$PROJECT_DIR/build-meta.json")
fi

if [ -z "$BE_PORT" ]; then
  log_error "Cannot determine backend port from build-meta.json"
  exit 1
fi

BASE_URL="http://localhost:$BE_PORT"
log_info "Testing against: $BASE_URL"

# ── Temp files for state (avoids subshell issues) ────────────

TOKEN_FILE=$(mktemp)
RESULTS_FILE=$(mktemp)
echo "[]" > "$RESULTS_FILE"
echo "" > "$TOKEN_FILE"
trap "rm -f $TOKEN_FILE $RESULTS_FILE" EXIT

# ── Helper: append test result ───────────────────────────────

append_result() {
  local id="$1" title="$2" status="$3" expected_status="$4" actual_status="$5" detail="$6"

  local current
  current=$(cat "$RESULTS_FILE")
  echo "$current" | jq --arg id "$id" --arg title "$title" \
    --arg status "$status" --arg expected "$expected_status" \
    --arg actual "$actual_status" --arg detail "$detail" \
    '. + [{
      id: $id,
      title: $title,
      status: $status,
      expected_status: ($expected | tonumber? // $expected),
      actual_status: ($actual | tonumber? // $actual),
      detail: $detail
    }]' > "$RESULTS_FILE"
}

# ── Helper: run one API test ─────────────────────────────────

run_api_test() {
  local id="$1" title="$2" method="$3" path="$4" body="$5" \
        expected_status="$6" expected_contains="$7" use_auth="$8"

  local url="${BASE_URL}${path}"
  local curl_args=(-s -w "\n%{http_code}" -X "$method" --max-time 10)

  # Add auth header if we have a token and test needs it
  local token
  token=$(cat "$TOKEN_FILE")
  if [ "$use_auth" = "true" ] && [ -n "$token" ]; then
    curl_args+=(-H "Authorization: Bearer $token")
  fi

  # Add JSON body if present
  if [ -n "$body" ] && [ "$body" != "null" ] && [ "$body" != "{}" ]; then
    curl_args+=(-H "Content-Type: application/json" -d "$body")
  fi

  # Execute request
  local response
  response=$(curl "${curl_args[@]}" "$url" 2>/dev/null) || {
    log_warn "  ✗ $id: $title — connection failed"
    append_result "$id" "$title" "FAIL" "$expected_status" "0" "Connection failed"
    return 1
  }

  # Split response body and status code
  local http_code
  http_code=$(echo "$response" | tail -1)
  local resp_body
  resp_body=$(echo "$response" | sed '$d')

  # Check status code (accept 200↔201 as equivalent)
  local status_ok="false"
  if [ "$http_code" = "$expected_status" ]; then
    status_ok="true"
  elif { [ "$http_code" = "200" ] && [ "$expected_status" = "201" ]; } || \
       { [ "$http_code" = "201" ] && [ "$expected_status" = "200" ]; }; then
    status_ok="true"
  fi

  if [ "$status_ok" = "false" ]; then
    local snippet
    snippet=$(echo "$resp_body" | head -c 200)
    log_warn "  ✗ $id: $title — expected $expected_status, got $http_code"
    append_result "$id" "$title" "FAIL" "$expected_status" "$http_code" "$snippet"
    return 1
  fi

  # Check expected body contents
  if [ -n "$expected_contains" ] && [ "$expected_contains" != "null" ] && [ "$expected_contains" != "[]" ]; then
    local missing=""
    local key
    while IFS= read -r key; do
      if [ -n "$key" ] && ! echo "$resp_body" | grep -qi "$key"; then
        missing="${missing}${key}, "
      fi
    done < <(echo "$expected_contains" | jq -r '.[]' 2>/dev/null)

    if [ -n "$missing" ]; then
      log_warn "  ✗ $id: $title — missing in response: ${missing%, }"
      append_result "$id" "$title" "FAIL" "$expected_status" "$http_code" "Missing: ${missing%, }"
      return 1
    fi
  fi

  # Extract token if this is a login/register response
  local token_candidate
  token_candidate=$(echo "$resp_body" | jq -r '
    .token // .data.token // .accessToken // .data.accessToken //
    .access_token // .data.access_token // empty' 2>/dev/null || true)
  if [ -n "$token_candidate" ] && [ "$token_candidate" != "null" ]; then
    echo "$token_candidate" > "$TOKEN_FILE"
  fi

  log_success "  ✓ $id: $title ($http_code)"
  append_result "$id" "$title" "PASS" "$expected_status" "$http_code" ""
  return 0
}

# ── Helper: process test cases from jq output ────────────────

run_tests_from_filter() {
  local filter="$1"
  local default_auth="$2"

  while IFS= read -r tc; do
    [ -z "$tc" ] && continue
    local id title method path body expected contains tc_type use_auth

    id=$(echo "$tc" | jq -r '.id')
    title=$(echo "$tc" | jq -r '.title')
    method=$(echo "$tc" | jq -r '.api_details.method // "GET"')
    path=$(echo "$tc" | jq -r '.api_details.path')
    body=$(echo "$tc" | jq -c '.api_details.body // {}')
    expected=$(echo "$tc" | jq -r '.api_details.expected_status // 200')
    contains=$(echo "$tc" | jq -c '.api_details.expected_body_contains // []')

    # Auth tests expecting 401/403 about "no token" should skip auth
    use_auth="$default_auth"
    if [ "$expected" = "401" ] || [ "$expected" = "403" ]; then
      if echo "$title" | grep -qi "without\|unauthorized\|no token\|missing.*token"; then
        use_auth="false"
      fi
    fi

    run_api_test "$id" "$title" "$method" "$path" "$body" "$expected" "$contains" "$use_auth" || true

  done < <(jq -c "$filter" "$TASKS_FILE")
}

# ══════════════════════════════════════════════════════════════
# TEST EXECUTION
# ══════════════════════════════════════════════════════════════

# ── Smoke test: health endpoint ──────────────────────────────

log_substep "Smoke test..."

HEALTH_RESP=$(curl -s -o /dev/null -w "%{http_code}" --max-time 10 "$BASE_URL/api/health" 2>/dev/null || echo "000")

if [ "$HEALTH_RESP" = "200" ]; then
  log_success "  ✓ SMOKE-01: GET /api/health → 200"
  append_result "SMOKE-01" "Health endpoint" "PASS" "200" "$HEALTH_RESP" ""
else
  # Try without /api prefix
  HEALTH_RESP=$(curl -s -o /dev/null -w "%{http_code}" --max-time 10 "$BASE_URL/health" 2>/dev/null || echo "000")
  if [ "$HEALTH_RESP" = "200" ]; then
    log_success "  ✓ SMOKE-01: GET /health → 200"
    append_result "SMOKE-01" "Health endpoint" "PASS" "200" "$HEALTH_RESP" ""
  else
    log_warn "  ✗ SMOKE-01: Health endpoint — got $HEALTH_RESP"
    append_result "SMOKE-01" "Health endpoint" "FAIL" "200" "$HEALTH_RESP" "Neither /api/health nor /health returned 200"
  fi
fi

# ── SpecPilot test cases ─────────────────────────────────────

if [ -n "$TASKS_FILE" ]; then

  TOTAL_TESTS=$(jq '[.test_cases[] | select(.api_details != null)] | length' "$TASKS_FILE")
  log_substep "Running $TOTAL_TESTS API test cases from SpecPilot..."

  # Phase 1: Register tests
  log_info "Phase 1: Authentication tests"
  run_tests_from_filter \
    '.test_cases[] | select(.api_details != null) | select(.api_details.path | test("register"; "i"))' \
    "false"

  # Phase 1b: Login tests (successful ones — to get token)
  run_tests_from_filter \
    '.test_cases[] | select(.api_details != null) | select(.api_details.path | test("login"; "i"))' \
    "false"

  # If we still don't have a token, try default seed credentials
  if [ -z "$(cat "$TOKEN_FILE")" ]; then
    log_info "  No token from test cases — trying seed credentials..."
    seed_response=$(curl -s -w "\n%{http_code}" -X POST \
      -H "Content-Type: application/json" \
      -d '{"email":"admin@demo.com","password":"demo123"}' \
      "$BASE_URL/api/auth/login" --max-time 10 2>/dev/null || true)

    seed_code=$(echo "$seed_response" | tail -1)
    seed_body=$(echo "$seed_response" | sed '$d')

    if [ "$seed_code" = "200" ] || [ "$seed_code" = "201" ]; then
      seed_token=$(echo "$seed_body" | jq -r '
        .token // .data.token // .accessToken // .data.accessToken //
        .access_token // .data.access_token // empty' 2>/dev/null || true)
      if [ -n "$seed_token" ] && [ "$seed_token" != "null" ]; then
        echo "$seed_token" > "$TOKEN_FILE"
        log_success "  Authenticated with seed admin account"
      fi
    fi
  fi

  # Phase 2: All other API tests (with auth)
  log_info "Phase 2: CRUD & business logic tests"
  run_tests_from_filter \
    '.test_cases[] | select(.api_details != null) | select(.api_details.path | test("(register|login)"; "i") | not)' \
    "true"

fi

# ── Compute summary from results file ────────────────────────

TOTAL=$(jq 'length' "$RESULTS_FILE")
PASSED=$(jq '[.[] | select(.status == "PASS")] | length' "$RESULTS_FILE")
FAILED=$(jq '[.[] | select(.status == "FAIL")] | length' "$RESULTS_FILE")
SKIPPED=$(jq '[.[] | select(.status == "SKIP")] | length' "$RESULTS_FILE")

PASS_RATE=0
if [ "$TOTAL" -gt 0 ]; then
  PASS_RATE=$(( (PASSED * 100) / TOTAL ))
fi

# ── Generate test report ─────────────────────────────────────

REPORT_FILE="$PROJECT_DIR/test-report.json"
RESULTS_CONTENT=$(cat "$RESULTS_FILE")

cat > "$REPORT_FILE" <<REPORT
{
  "stage": "test",
  "timestamp": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
  "base_url": "$BASE_URL",
  "test_source": "${TASKS_FILE:-smoke-only}",
  "summary": {
    "total": $TOTAL,
    "passed": $PASSED,
    "failed": $FAILED,
    "skipped": $SKIPPED,
    "pass_rate": $PASS_RATE
  },
  "results": $RESULTS_CONTENT
}
REPORT

# ── Print summary ────────────────────────────────────────────

log_info ""
log_info "┌─────────────────────────────────────┐"
log_info "│         TEST RESULTS                │"
log_info "├─────────────────────────────────────┤"

if [ "$FAILED" -gt 0 ]; then
  log_warn "│  Total:   $TOTAL"
  log_warn "│  Passed:  $PASSED ✓"
  log_warn "│  Failed:  $FAILED ✗"
  log_warn "│  Rate:    ${PASS_RATE}%"
else
  log_success "│  Total:   $TOTAL"
  log_success "│  Passed:  $PASSED ✓"
  log_success "│  Failed:  $FAILED ✗"
  log_success "│  Rate:    ${PASS_RATE}%"
fi

log_info "└─────────────────────────────────────┘"
log_info "Report: $REPORT_FILE"

# ── Update build-meta with test results ──────────────────────

if [ -f "$PROJECT_DIR/build-meta.json" ]; then
  jq --argjson total "$TOTAL" --argjson passed "$PASSED" \
     --argjson failed "$FAILED" --argjson rate "$PASS_RATE" \
    '.test_results = {total: $total, passed: $passed, failed: $failed, pass_rate: $rate}' \
    "$PROJECT_DIR/build-meta.json" > "$PROJECT_DIR/build-meta.json.tmp" && \
    mv "$PROJECT_DIR/build-meta.json.tmp" "$PROJECT_DIR/build-meta.json"
fi

# ── Exit ─────────────────────────────────────────────────────

if [ "$FAILED" -gt 0 ]; then
  log_warn "Test stage completed with $FAILED failure(s)"
fi

log_success "Test stage complete"
exit 0
